services:
  ai-gateway:
    build: .
    container_name: ai-gateway
    restart: unless-stopped

    user: "1000:1000"

    env_file:
      - .env

    ports:
      - "3010:8080"

    environment:
      DOCUMENTS_ROOT: /documents

    volumes:
      - ./data:/app/data
      - /home/homelabuser/RemoteDrop/Audio:/remote/Audio
      - /home/homelabuser/RemoteDrop/Documents:/documents:ro

    networks:
      - ai-network

networks:
  ai-network:
    external: true
